# Week 2 - Data Analysis
#### Part 1
### Notebook created by Jonathan Penava and modified by Simon Hood
By the end of this lesson you should be able to read in a data set from a CSV file into a DataFrame, and manipulate that DataFrame.

## Overview
- <span style="color:red;">NumPy</span>
- Pandas
- Data Frames
- Reading CSV

### NumPy

In this part we want to look at NumPy arrays and some functionality.  This is the first step towards building Data Frames. <br>

Additional resources on NumPy:</br>
<a href="https://numpy.org/">NumPy</a></br>
</br>
What is NumPy?</br>
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. </br> (Copied from <a href="https://numpy.org/doc/stable/">NumPy Documentation</a>)

In [1]:
import numpy as np   #Import the NumPy library

In [2]:
newList = [1,2,3]    #Python list

We can create a NumPy array from a Python list

In [3]:
np.array(newList)    #NumPy array

array([1, 2, 3])

#### Some Built In NumPy Functions

In [4]:
np.arange(0,10)    #Generate an array from 0-9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)   #Generate an array from 0-10 step by 2

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.random.rand(10)   #Generate an array size 10 of random numbers from 0-1

array([0.73119114, 0.5843607 , 0.67828374, 0.90166111, 0.55656463,
       0.49698296, 0.62793208, 0.0840498 , 0.02856872, 0.55218349])

In [8]:
np.random.rand(10)*10   #Generate an array like above but from 0-10

array([7.81648755, 7.06181958, 3.09590596, 9.3474321 , 2.43188055,
       8.61273907, 9.97911587, 5.70191034, 0.22622985, 7.34194183])

In [11]:
np.random.rand(4,4)   #Generate a 2 dimensional array of size 4 by 4

array([[0.33595695, 0.29766407, 0.79741353, 0.35843867],
       [0.03340973, 0.66951729, 0.09985367, 0.66677807],
       [0.36406546, 0.73428409, 0.47984576, 0.325937  ],
       [0.61531235, 0.60338866, 0.45844797, 0.23909818]])

In [12]:
np.random.randint(1,100,10)   #Generate an integer array from 1-100 of size 10

array([80, 96, 73, 43, 35, 19, 22, 70, 39, 32])

In [14]:
myIntArray = np.random.randint(1,100,10)  #Results of operations can, and maybe should, be stored in varaibles
myIntArray

array([ 3, 67, 10, 98, 93, 52, 74, 54, 71, 40])

In [15]:
myIntArray.max()  #The max value in the array  

98

In [17]:
myIntArray.argmax()  #The index of the max value

3

In [18]:
myIntArray.min()  #The minimum value

3

In [19]:
myIntArray.argmin()  #The index of the min value

0

In [20]:
myIntArray[3]  #The value at index 3

98

In [21]:
myIntArray[2:5]  #The values at index 2-4

array([10, 98, 93])

There are many more built in commands for NumPy.  I encourage you to explore on your own.  You can find additional resources at https://numpy.org/doc/stable/